In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

df

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [3]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   14 non-null     int64
dtypes: int64(1), str(2)
memory usage: 468.0 bytes

In [14]:
df.at[4, 'Units Sold']

np.int64(35)

In [21]:
df.replace(35, 14, inplace=True)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          14
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          14
10   Saturday    Espresso          45
11   Saturday       Latte          14
12     Sunday    Espresso          45
13     Sunday       Latte          14

In [22]:
df

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          14
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          14
10   Saturday    Espresso          45
11   Saturday       Latte          14
12     Sunday    Espresso          45
13     Sunday       Latte          14

In [35]:
df[0:5][['Day','Units Sold']]

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          14

In [42]:
df.loc[df['Units Sold'] == 14]

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          14
9      Friday       Latte          14
11   Saturday       Latte          14
13     Sunday       Latte          14

In [45]:
df.loc[0:, ['Day', 'Units Sold']]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          14
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          14
10   Saturday          45
11   Saturday          14
12     Sunday          45
13     Sunday          14

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv')

In [47]:
df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [48]:
df.tail()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [63]:
df.describe()

                year     athlete_id          place
count  305807.000000  308408.000000  283193.000000
mean     1982.239223   72624.097125      16.102764
std        30.983982   41285.940841      19.322611
min      1896.000000       1.000000       1.000000
25%      1964.000000   34412.000000       5.000000
50%      1992.000000   73739.500000       9.000000
75%      2008.000000  107168.000000      20.000000
max      2022.000000  148986.000000     185.000000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  str
 2   discipline  308407 non-null  str
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  str
 7   team        121714 non-null  str
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   str
dtypes: bool(1), float64(2), int64(1), str(7)
memory usage: 23.8 MB

In [5]:
df[(df['event'].str.contains('women', case=False)) & (df['as'].str.contains("helen", case=False)) & (df['discipline'] == 'Tennis')]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
144,1912.0,Summer,Tennis,"Singles, Covered Courts, Women (Olympic)",Helen Aitchison,38,GBR,NaN,5.0,True,NaN
1861,1988.0,Summer,Tennis,"Singles, Women (Olympic)",Helen Kelesi,739,CAN,NaN,33.0,True,NaN
4731,1988.0,Summer,Tennis,"Singles, Women (Olympic)",Helena Suková,2353,TCH,NaN,17.0,True,NaN
4732,1988.0,Summer,Tennis,"Doubles, Women (Olympic)",Helena Suková,2353,TCH,Jana Novotná,2.0,False,Silver
4733,1992.0,Summer,Tennis,"Singles, Women (Olympic)",Helena Suková,2353,TCH,NaN,17.0,True,NaN
4734,1996.0,Summer,Tennis,"Singles, Women (Olympic)",Helena Suková,2353,CZE,NaN,33.0,True,NaN
4735,1996.0,Summer,Tennis,"Doubles, Women (Olympic)",Helena Suková,2353,CZE,Jana Novotná,2.0,False,Silver
5756,1924.0,Summer,Tennis,"Singles, Women (Olympic)",Helen Wills,2744,USA,NaN,1.0,False,Gold
5757,1924.0,Summer,Tennis,"Doubles, Women (Olympic)",Helen Wills,2744,USA,Hazel Wightman,1.0,False,Gold

In [6]:
df[df['team'].notna() & df['team'].isin(['India', 'USA'])]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
3739,1992.0,Summer,Archery,"Team, Men (Olympic)",Dhulchand Damor,1898,IND,India,16.0,False,NaN
3741,1996.0,Summer,Archery,"Team, Men (Olympic)",Skalzang Dorje,1899,IND,India,14.0,False,NaN
3743,1992.0,Summer,Archery,"Team, Men (Olympic)",Changte Lalremsaga,1900,IND,India,16.0,False,NaN
3745,1996.0,Summer,Archery,"Team, Men (Olympic)",Changte Lalremsaga,1900,IND,India,14.0,False,NaN
3747,1988.0,Summer,Archery,"Team, Men (Olympic)",Limba Ram,1901,IND,India,20.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
301691,2020.0,Summer,Hockey,"Hockey, Men (Olympic)",Shamsher Singh,143777,IND,India,3.0,False,Bronze
301692,2020.0,Summer,Hockey,"Hockey, Men (Olympic)",Sumit,143778,IND,India,3.0,False,Bronze
306370,2020.0,Summer,Hockey,"Hockey, Women (Olympic)",Reena Khokhar,147731,IND,India,NaN,False,NaN
306403,2020.0,Summer,Hockey,"Hockey, Men (Olympic)",Simranjeet Singh,147765,IND,India,3.0,False,Bronze
306404,2020.0,Summer,Hockey,"Hockey, Men (Olympic)",Varun Kumar,147766,IND,India,3.0,False,Bronze

In [ ]:
df[df['team'].isin(['India'])]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
3739,1992.0,Summer,Archery,"Team, Men (Olympic)",Dhulchand Damor,1898,IND,India,16.0,False,NaN
3741,1996.0,Summer,Archery,"Team, Men (Olympic)",Skalzang Dorje,1899,IND,India,14.0,False,NaN
3743,1992.0,Summer,Archery,"Team, Men (Olympic)",Changte Lalremsaga,1900,IND,India,16.0,False,NaN
3745,1996.0,Summer,Archery,"Team, Men (Olympic)",Changte Lalremsaga,1900,IND,India,14.0,False,NaN
3747,1988.0,Summer,Archery,"Team, Men (Olympic)",Limba Ram,1901,IND,India,20.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
301691,2020.0,Summer,Hockey,"Hockey, Men (Olympic)",Shamsher Singh,143777,IND,India,3.0,False,Bronze
301692,2020.0,Summer,Hockey,"Hockey, Men (Olympic)",Sumit,143778,IND,India,3.0,False,Bronze
306370,2020.0,Summer,Hockey,"Hockey, Women (Olympic)",Reena Khokhar,147731,IND,India,NaN,False,NaN
306403,2020.0,Summer,Hockey,"Hockey, Men (Olympic)",Simranjeet Singh,147765,IND,India,3.0,False,Bronze
306404,2020.0,Summer,Hockey,"Hockey, Men (Olympic)",Varun Kumar,147766,IND,India,3.0,False,Bronze

In [7]:
df_clean = df.copy()

In [15]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  str
 2   discipline  308407 non-null  str
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  str
 7   team        121714 non-null  str
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   str
dtypes: bool(1), float64(2), int64(1), str(7)
memory usage: 23.8 MB

In [ ]:
df_clean.drop(columns=['noc', 'tied'])

,year,type,discipline,event,as,athlete_id,team,place,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,NaN,17.0,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,Jean Montariol,NaN,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,NaN,32.0,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,Jeanne Vaussard,8.0,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,Jacques Brugnon,4.0,NaN
...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,NaN,26.0,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,NaN,28.0,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,Sweden,13.0,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,NaN,NaN,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,24.0,NaN

In [9]:
df_new = df.dropna()

In [10]:
df_new

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
9,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean Borotra,3,FRA,René Lacoste,3.0,False,Bronze
12,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jacques Brugnon,4,FRA,Henri Cochet,2.0,False,Silver
14,1912.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Albert Canet,5,FRA,Marguerite Broquedis,3.0,False,Bronze
15,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Albert Canet,5,FRA,Édouard Mény de Marangue,3.0,False,Bronze
21,2000.0,Summer,Table Tennis,"Doubles, Men (Olympic)",Patrick Chila,7,FRA,Jean-Philippe Gatien,3.0,False,Bronze
...,...,...,...,...,...,...,...,...,...,...,...
308398,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Miloš Roman,148978,SVK,Slovakia,3.0,False,Bronze
308399,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Juraj Slafkovský,148979,SVK,Slovakia,3.0,False,Bronze
308400,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Samuel Takáč,148980,SVK,Slovakia,3.0,False,Bronze
308401,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Matej Tomek,148981,SVK,Slovakia,3.0,False,Bronze
308402,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Peter Zuzin,148982,SVK,Slovakia,3.0,False,Bronze

In [11]:
df_new['Medal'] = df_new['medal'].apply(lambda x: '🥇' if x == 'Gold' else '🏆')

In [12]:
df_new

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,Medal
9,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean Borotra,3,FRA,René Lacoste,3.0,False,Bronze,🏆
12,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jacques Brugnon,4,FRA,Henri Cochet,2.0,False,Silver,🏆
14,1912.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Albert Canet,5,FRA,Marguerite Broquedis,3.0,False,Bronze,🏆
15,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Albert Canet,5,FRA,Édouard Mény de Marangue,3.0,False,Bronze,🏆
21,2000.0,Summer,Table Tennis,"Doubles, Men (Olympic)",Patrick Chila,7,FRA,Jean-Philippe Gatien,3.0,False,Bronze,🏆
...,...,...,...,...,...,...,...,...,...,...,...,...
308398,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Miloš Roman,148978,SVK,Slovakia,3.0,False,Bronze,🏆
308399,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Juraj Slafkovský,148979,SVK,Slovakia,3.0,False,Bronze,🏆
308400,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Samuel Takáč,148980,SVK,Slovakia,3.0,False,Bronze,🏆
308401,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Matej Tomek,148981,SVK,Slovakia,3.0,False,Bronze,🏆
308402,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Peter Zuzin,148982,SVK,Slovakia,3.0,False,Bronze,🏆

In [13]:
df_new[df_new['Medal'] == '🥇']
df_new.drop(columns=['medal'], inplace=True)
df_new

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,Medal
9,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean Borotra,3,FRA,René Lacoste,3.0,False,🏆
12,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jacques Brugnon,4,FRA,Henri Cochet,2.0,False,🏆
14,1912.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Albert Canet,5,FRA,Marguerite Broquedis,3.0,False,🏆
15,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Albert Canet,5,FRA,Édouard Mény de Marangue,3.0,False,🏆
21,2000.0,Summer,Table Tennis,"Doubles, Men (Olympic)",Patrick Chila,7,FRA,Jean-Philippe Gatien,3.0,False,🏆
...,...,...,...,...,...,...,...,...,...,...,...
308398,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Miloš Roman,148978,SVK,Slovakia,3.0,False,🏆
308399,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Juraj Slafkovský,148979,SVK,Slovakia,3.0,False,🏆
308400,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Samuel Takáč,148980,SVK,Slovakia,3.0,False,🏆
308401,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Matej Tomek,148981,SVK,Slovakia,3.0,False,🏆
308402,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Peter Zuzin,148982,SVK,Slovakia,3.0,False,🏆

In [15]:
emp = pd.read_csv('employees.csv')
dept = pd.read_csv('departments.csv')

In [16]:
emp

   id             name  age  department_id  salary
0   1    Alice Johnson   30              1   85000
1   2        Bob Smith   25              2   60000
2   3    Charlie Brown   35              1   95000
3   4     Diana Prince   28              3   70000
4   5    Edward Norton   40              4   80000
5   6  Fiona Gallagher   32              2   65000
6   7    George Miller   45              5  105000
7   8    Hannah Abbott   27              3   72000

In [17]:
dept

   id         name
0   1  Engineering
1   2    Marketing
2   3        Sales
3   4           HR
4   5      Finance

In [29]:
emp.groupby('department_id')['age'].max()

department_id
1    35
2    32
3    28
4    40
5    45
Name: age, dtype: int64

In [26]:
emp

   id             name  age  department_id  salary
0   1    Alice Johnson   30              1   85000
1   2        Bob Smith   25              2   60000
2   3    Charlie Brown   35              1   95000
3   4     Diana Prince   28              3   70000
4   5    Edward Norton   40              4   80000
5   6  Fiona Gallagher   32              2   65000
6   7    George Miller   45              5  105000
7   8    Hannah Abbott   27              3   72000

In [30]:
merged_df = pd.merge(emp, dept, left_on='department_id', right_on='id', how='left')
merged_df

   id_x           name_x  age  department_id  salary  id_y       name_y
0     1    Alice Johnson   30              1   85000     1  Engineering
1     2        Bob Smith   25              2   60000     2    Marketing
2     3    Charlie Brown   35              1   95000     1  Engineering
3     4     Diana Prince   28              3   70000     3        Sales
4     5    Edward Norton   40              4   80000     4           HR
5     6  Fiona Gallagher   32              2   65000     2    Marketing
6     7    George Miller   45              5  105000     5      Finance
7     8    Hannah Abbott   27              3   72000     3        Sales

In [18]:
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30],
    'City': ['New York', 'London'],
    'salary': [70000, 80000]
})
df1

    Name  Age      City  salary
0  Alice   25  New York   70000
1    Bob   30    London   80000

In [19]:
df2 = pd.DataFrame({
    'Name': ['Charlie', 'David', 'Grace', 'Heidi'],
    'Age': [35, 40, 29, 31],
    'City': ['Paris', 'Tokyo', 'Rome', 'Madrid'],
    'salary': [90000, 100000, 85000, 95000]
})
df2

      Name  Age    City  salary
0  Charlie   35   Paris   90000
1    David   40   Tokyo  100000
2    Grace   29    Rome   85000
3    Heidi   31  Madrid   95000

In [20]:
df = pd.concat([df1, df2])
df

      Name  Age      City  salary
0    Alice   25  New York   70000
1      Bob   30    London   80000
0  Charlie   35     Paris   90000
1    David   40     Tokyo  100000
2    Grace   29      Rome   85000
3    Heidi   31    Madrid   95000

In [21]:
df['Rank'] = df['salary'].rank(ascending=False, method='dense')
df

      Name  Age      City  salary  Rank
0    Alice   25  New York   70000   6.0
1      Bob   30    London   80000   5.0
0  Charlie   35     Paris   90000   3.0
1    David   40     Tokyo  100000   1.0
2    Grace   29      Rome   85000   4.0
3    Heidi   31    Madrid   95000   2.0

In [31]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 90, 78],
    'Science': [92, 88, 95],
    'English': [80, 85, 82]
})

df

      Name  Math  Science  English
0    Alice    85       92       80
1      Bob    90       88       85
2  Charlie    78       95       82

In [ ]:

melted_df = pd.melt(df, id_vars = ['Name'], var_name = 'Subject', value_name = 'Score')
melted_df

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     90
2  Charlie     Math     78
3    Alice  Science     92
4      Bob  Science     88
5  Charlie  Science     95
6    Alice  English     80
7      Bob  English     85
8  Charlie  English     82

In [35]:
pivot_table_df = pd.pivot_table(melted_df, index='Name', values='Score', aggfunc='sum')
pivot_table_df

         Score
Name
Alice      257
Bob        263
Charlie    255